class Config:
    ZOOM_FACTOR = 1
    TILE_WIDTH = 32 * ZOOM_FACTOR
    TILE_HEIGHT = TILE_WIDTH / 2 * ZOOM_FACTOR
    ROW = 20 
    COL = 20
    FULL_WIDTH = TILE_WIDTH * ROW * ZOOM_FACTOR
    FULL_HEIGHT = TILE_HEIGHT * COL * ZOOM_FACTOR
    HALF_WIDTH = FULL_WIDTH / 2 * ZOOM_FACTOR
    HALF_HEIGHT = FULL_HEIGHT / 2 * ZOOM_FACTOR
    TILE_COUNT = ROW * COL 
    X_OFFSET = (TILE_WIDTH * ROW / 2) * ZOOM_FACTOR
    Y_OFFSET = -1 * TILE_HEIGHT * ZOOM_FACTOR
    ADJ_Y_OFFSET = 22 * ZOOM_FACTOR
